id: P008125
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W3CN2406
  title: འབྲུག་ལུགས་འདོན་ཆོག་ཕྱོགས་བསྡུས།
  author: ''
  volumes:
    111811618ef9424e8767a2ce5662c680:
      image_group_id: I3CN2408
      title: Volume 1 of 'brug lugs 'don chog phyogs bsdus/
      volume_number: 1
      total_pages: 816
      base_file: v001.txt
