id: P008125
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN2406
  title: འབྲུག་ལུགས་འདོན་ཆོག་ཕྱོགས་བསྡུས།
  author: ''
  volumes:
    c3bcb0fded8c4e359f6b34ef689bc9ff:
      image_group_id: I3CN2408
      title: ''
      volume_number: 1
      total_pages: 816
ebook_metadata:
  title: འབྲུག་ལུགས་འདོན་ཆོག་ཕྱོགས་བསྡུས།
  author: ''
  sku: P008125
  cover: cover.jpg
  layers:
  - pagination
