id: I7A339694
legacy_id: P008125
ocr_import_info:
  bdrc_scan_id: W3CN2406
  source: bdrc
  ocr_info:
    timestamp: '2020-03-27T01:31:03'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T13:08:08.822655+00:00'
last_modified: 2022-09-03 21:08:29.341452
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN2406
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW3CN2406
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: འབྲུག་ལུགས་འདོན་ཆོག་ཕྱོགས་བསྡུས།
statistics:
  ocr_word_mean_confidence_index: 0.6796764857614633
  ocr_word_median_confidence_index: 0.75
quality: null
bases:
  I3CN2408:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN2408
      total_pages: 816
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN2408.txt
    statistics:
      ocr_word_median_confidence_index: 0.75
      ocr_word_mean_confidence_index: 0.6796764857614633
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
